/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityItem {
  'id' : bigint,
  'activityType' : ActivityType,
  'relatedDocumentId' : [] | [DocumentId],
  'description' : string,
  'timestamp' : Timestamp,
}
export type ActivityType = { 'documentUploaded' : null } |
  { 'complianceChecked' : null } |
  { 'entityExtracted' : null } |
  { 'relationshipCreated' : null } |
  { 'chatCreated' : null } |
  { 'documentProcessed' : null } |
  { 'incidentRecorded' : null } |
  { 'analysisRun' : null };
export type AppError = { 'storageError' : null } |
  { 'processingError' : null } |
  { 'alreadyExists' : null } |
  { 'invalidInput' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface CauseAnalysis {
  'probability' : number,
  'cause' : string,
  'supportingEvidence' : Array<string>,
}
export interface ChatMessage {
  'id' : ChatMessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'sources' : Array<SourceCitation>,
  'confidence' : [] | [number],
  'threadId' : ChatThreadId,
}
export type ChatMessageId = bigint;
export interface ChatThread {
  'id' : ChatThreadId,
  'title' : string,
  'owner' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ChatThreadId = bigint;
export type ChunkId = bigint;
export type ComplianceCheckId = bigint;
export interface ComplianceFinding {
  'id' : ComplianceCheckId,
  'status' : FindingStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'documentId' : DocumentId,
  'severity' : Severity,
  'findingType' : string,
}
export interface ComplianceGap {
  'requirement' : string,
  'missingIn' : string,
  'severity' : Severity,
}
export interface ComplianceResult {
  'checkId' : ComplianceCheckId,
  'gaps' : Array<ComplianceGap>,
  'generatedAt' : Timestamp,
  'violations' : Array<ComplianceViolation>,
  'documentId' : DocumentId,
  'complianceScore' : number,
  'riskLevel' : RiskLevel,
  'suggestedCorrections' : Array<string>,
}
export interface ComplianceViolation {
  'violation' : string,
  'rule' : string,
  'severity' : Severity,
  'location' : string,
}
export interface DashboardStats {
  'totalChatThreads' : bigint,
  'totalComplianceChecks' : bigint,
  'recentUploads' : bigint,
  'totalEntities' : bigint,
  'totalIncidents' : bigint,
  'totalDocuments' : bigint,
  'documentsProcessed' : bigint,
  'totalRelationships' : bigint,
}
export interface Document {
  'id' : DocumentId,
  'status' : DocumentStatus,
  'owner' : Principal,
  'metadata' : DocumentMetadata,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'mimeType' : string,
  'extractedText' : [] | [string],
  'filename' : string,
  'updatedAt' : Timestamp,
}
export interface DocumentChunk {
  'id' : ChunkId,
  'content' : string,
  'chunkIndex' : bigint,
  'createdAt' : Timestamp,
  'embedding' : [] | [Array<number>],
  'documentId' : DocumentId,
}
export type DocumentId = bigint;
export interface DocumentMetadata {
  'assetNames' : Array<string>,
  'fileSize' : bigint,
  'personnel' : Array<string>,
  'failureTypes' : Array<string>,
  'maintenanceEvents' : Array<string>,
  'safetyReferences' : Array<string>,
  'dates' : Array<string>,
  'pageCount' : [] | [bigint],
  'equipmentIds' : Array<string>,
  'regulatoryReferences' : Array<string>,
}
export type DocumentStatus = { 'chunked' : null } |
  { 'error' : null } |
  { 'extracted' : null } |
  { 'uploaded' : null } |
  { 'processing' : null } |
  { 'embedded' : null } |
  { 'ready' : null };
export interface DocumentSummary {
  'id' : DocumentId,
  'status' : DocumentStatus,
  'createdAt' : Timestamp,
  'mimeType' : string,
  'filename' : string,
}
export interface Entity {
  'id' : EntityId,
  'sourceDocumentId' : [] | [DocumentId],
  'name' : string,
  'createdAt' : Timestamp,
  'properties' : Array<[string, string]>,
  'entityType' : EntityType,
}
export type EntityId = bigint;
export type EntityType = { 'failure' : null } |
  { 'asset' : null } |
  { 'regulation' : null } |
  { 'other' : null } |
  { 'equipment' : null } |
  { 'person' : null } |
  { 'event' : null } |
  { 'document' : null } |
  { 'procedure' : null } |
  { 'location' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface EvidenceItem {
  'documentName' : string,
  'relevanceScore' : number,
  'excerpt' : string,
  'documentId' : DocumentId,
}
export type ExternalBlob = Uint8Array;
export type FindingStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inReview' : null } |
  { 'dismissed' : null };
export interface GraphData {
  'edges' : Array<GraphEdge>,
  'nodes' : Array<GraphNode>,
}
export interface GraphEdge {
  'id' : RelationshipId,
  'source' : EntityId,
  'target' : EntityId,
  'edgeLabel' : string,
  'confidence' : number,
  'relationshipType' : RelationshipType,
}
export interface GraphNode {
  'id' : EntityId,
  'nodeLabel' : string,
  'properties' : Array<[string, string]>,
  'entityType' : EntityType,
}
export type IncidentId = bigint;
export interface IncidentRecord {
  'id' : IncidentId,
  'title' : string,
  'sourceDocumentId' : [] | [DocumentId],
  'date' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'severity' : Severity,
  'equipmentId' : [] | [string],
  'incidentType' : string,
}
export interface LessonsLearnedResult {
  'patterns' : Array<PatternDetection>,
  'generatedAt' : Timestamp,
  'preventiveActions' : Array<PreventiveAction>,
  'analysisId' : bigint,
  'highRiskConditions' : Array<RiskCondition>,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface PatternDetection {
  'occurrenceCount' : bigint,
  'patternName' : string,
  'description' : string,
  'affectedEquipment' : Array<string>,
}
export interface PreventiveAction {
  'action' : string,
  'estimatedImpact' : string,
  'priority' : Priority,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export interface Relationship {
  'id' : RelationshipId,
  'sourceDocumentId' : [] | [DocumentId],
  'createdAt' : Timestamp,
  'sourceId' : EntityId,
  'confidence' : number,
  'targetId' : EntityId,
  'relationshipType' : RelationshipType,
}
export type RelationshipId = bigint;
export type RelationshipType = { 'leadsTo' : null } |
  { 'references' : null } |
  { 'other' : null } |
  { 'violates' : null } |
  { 'inspectedBy' : null } |
  { 'similarTo' : null } |
  { 'compliesWith' : null } |
  { 'maintainedBy' : null } |
  { 'locatedAt' : null } |
  { 'causes' : null } |
  { 'partOf' : null };
export type Result = { 'ok' : Document } |
  { 'err' : AppError };
export type Result_1 = { 'ok' : ChatMessage } |
  { 'err' : AppError };
export type Result_2 = { 'ok' : ComplianceResult } |
  { 'err' : AppError };
export type Result_3 = { 'ok' : IncidentRecord } |
  { 'err' : AppError };
export type Result_4 = { 'ok' : ComplianceFinding } |
  { 'err' : AppError };
export type Result_5 = { 'ok' : null } |
  { 'err' : AppError };
export type Result_6 = { 'ok' : Relationship } |
  { 'err' : AppError };
export type Result_7 = { 'ok' : Entity } |
  { 'err' : AppError };
export type Result_8 = { 'ok' : DocumentChunk } |
  { 'err' : AppError };
export type Result_9 = { 'ok' : Array<DocumentChunk> } |
  { 'err' : AppError };
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RiskCondition {
  'historicalIncidents' : Array<IncidentId>,
  'recommendation' : string,
  'riskLevel' : RiskLevel,
  'condition' : string,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface RootCauseResult {
  'userQuery' : string,
  'recommendedActions' : Array<string>,
  'generatedAt' : Timestamp,
  'similarFailures' : Array<SimilarFailure>,
  'confidenceScore' : number,
  'evidence' : Array<EvidenceItem>,
  'equipmentId' : [] | [string],
  'likelyCauses' : Array<CauseAnalysis>,
}
export type Severity = { 'major' : null } |
  { 'minor' : null } |
  { 'critical' : null } |
  { 'moderate' : null };
export interface SimilarFailure {
  'incidentId' : IncidentId,
  'date' : string,
  'similarityScore' : number,
  'description' : string,
  'equipmentId' : string,
}
export interface SourceCitation {
  'documentName' : string,
  'chunkIndex' : bigint,
  'excerpt' : string,
  'documentId' : DocumentId,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatThread' : ActorMethod<[string], ChatThread>,
  'createChunks' : ActorMethod<[DocumentId, Array<string>], Result_9>,
  'createEmbedding' : ActorMethod<[ChunkId, Array<number>], Result_8>,
  'createEntity' : ActorMethod<
    [string, EntityType, Array<[string, string]>, [] | [DocumentId]],
    Result_7
  >,
  'createRelationship' : ActorMethod<
    [EntityId, EntityId, RelationshipType, number, [] | [DocumentId]],
    Result_6
  >,
  'deleteDocument' : ActorMethod<[DocumentId], Result_5>,
  'extractText' : ActorMethod<[DocumentId, string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[ChatThreadId], Array<ChatMessage>>,
  'getChatThreads' : ActorMethod<[], Array<ChatThread>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDocument' : ActorMethod<[DocumentId], Result>,
  'getDocuments' : ActorMethod<[], Array<DocumentSummary>>,
  'getEntities' : ActorMethod<[[] | [EntityType]], Array<Entity>>,
  'getGraphData' : ActorMethod<[[] | [EntityId], bigint], GraphData>,
  'getRecentActivity' : ActorMethod<[bigint], Array<ActivityItem>>,
  'getRelationships' : ActorMethod<[[] | [EntityId]], Array<Relationship>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordComplianceFinding' : ActorMethod<
    [DocumentId, string, string, Severity, FindingStatus],
    Result_4
  >,
  'recordIncident' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      Severity,
      string,
      [] | [DocumentId],
    ],
    Result_3
  >,
  'runComplianceCheck' : ActorMethod<[DocumentId], Result_2>,
  'runLessonsLearnedAnalysis' : ActorMethod<[], LessonsLearnedResult>,
  'runRootCauseAnalysis' : ActorMethod<
    [string, [] | [string]],
    RootCauseResult
  >,
  'semanticSearch' : ActorMethod<[string, bigint], Array<DocumentChunk>>,
  'sendMessage' : ActorMethod<
    [ChatThreadId, MessageRole, string, Array<SourceCitation>, [] | [number]],
    Result_1
  >,
  'uploadDocument' : ActorMethod<
    [string, string, ExternalBlob, bigint],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];