/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatThreadId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const ChatThread = IDL.Record({
  'id' : ChatThreadId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const DocumentId = IDL.Nat;
export const ChunkId = IDL.Nat;
export const DocumentChunk = IDL.Record({
  'id' : ChunkId,
  'content' : IDL.Text,
  'chunkIndex' : IDL.Nat,
  'createdAt' : Timestamp,
  'embedding' : IDL.Opt(IDL.Vec(IDL.Float64)),
  'documentId' : DocumentId,
});
export const AppError = IDL.Variant({
  'storageError' : IDL.Null,
  'processingError' : IDL.Null,
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(DocumentChunk),
  'err' : AppError,
});
export const Result_8 = IDL.Variant({ 'ok' : DocumentChunk, 'err' : AppError });
export const EntityType = IDL.Variant({
  'failure' : IDL.Null,
  'asset' : IDL.Null,
  'regulation' : IDL.Null,
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'person' : IDL.Null,
  'event' : IDL.Null,
  'document' : IDL.Null,
  'procedure' : IDL.Null,
  'location' : IDL.Null,
});
export const EntityId = IDL.Nat;
export const Entity = IDL.Record({
  'id' : EntityId,
  'sourceDocumentId' : IDL.Opt(DocumentId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'entityType' : EntityType,
});
export const Result_7 = IDL.Variant({ 'ok' : Entity, 'err' : AppError });
export const RelationshipType = IDL.Variant({
  'leadsTo' : IDL.Null,
  'references' : IDL.Null,
  'other' : IDL.Null,
  'violates' : IDL.Null,
  'inspectedBy' : IDL.Null,
  'similarTo' : IDL.Null,
  'compliesWith' : IDL.Null,
  'maintainedBy' : IDL.Null,
  'locatedAt' : IDL.Null,
  'causes' : IDL.Null,
  'partOf' : IDL.Null,
});
export const RelationshipId = IDL.Nat;
export const Relationship = IDL.Record({
  'id' : RelationshipId,
  'sourceDocumentId' : IDL.Opt(DocumentId),
  'createdAt' : Timestamp,
  'sourceId' : EntityId,
  'confidence' : IDL.Float64,
  'targetId' : EntityId,
  'relationshipType' : RelationshipType,
});
export const Result_6 = IDL.Variant({ 'ok' : Relationship, 'err' : AppError });
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
export const DocumentStatus = IDL.Variant({
  'chunked' : IDL.Null,
  'error' : IDL.Null,
  'extracted' : IDL.Null,
  'uploaded' : IDL.Null,
  'processing' : IDL.Null,
  'embedded' : IDL.Null,
  'ready' : IDL.Null,
});
export const DocumentMetadata = IDL.Record({
  'assetNames' : IDL.Vec(IDL.Text),
  'fileSize' : IDL.Nat,
  'personnel' : IDL.Vec(IDL.Text),
  'failureTypes' : IDL.Vec(IDL.Text),
  'maintenanceEvents' : IDL.Vec(IDL.Text),
  'safetyReferences' : IDL.Vec(IDL.Text),
  'dates' : IDL.Vec(IDL.Text),
  'pageCount' : IDL.Opt(IDL.Nat),
  'equipmentIds' : IDL.Vec(IDL.Text),
  'regulatoryReferences' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : DocumentId,
  'status' : DocumentStatus,
  'owner' : IDL.Principal,
  'metadata' : DocumentMetadata,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'mimeType' : IDL.Text,
  'extractedText' : IDL.Opt(IDL.Text),
  'filename' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const Result = IDL.Variant({ 'ok' : Document, 'err' : AppError });
export const ChatMessageId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const SourceCitation = IDL.Record({
  'documentName' : IDL.Text,
  'chunkIndex' : IDL.Nat,
  'excerpt' : IDL.Text,
  'documentId' : DocumentId,
});
export const ChatMessage = IDL.Record({
  'id' : ChatMessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'sources' : IDL.Vec(SourceCitation),
  'confidence' : IDL.Opt(IDL.Float64),
  'threadId' : ChatThreadId,
});
export const DashboardStats = IDL.Record({
  'totalChatThreads' : IDL.Nat,
  'totalComplianceChecks' : IDL.Nat,
  'recentUploads' : IDL.Nat,
  'totalEntities' : IDL.Nat,
  'totalIncidents' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
  'documentsProcessed' : IDL.Nat,
  'totalRelationships' : IDL.Nat,
});
export const DocumentSummary = IDL.Record({
  'id' : DocumentId,
  'status' : DocumentStatus,
  'createdAt' : Timestamp,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const GraphEdge = IDL.Record({
  'id' : RelationshipId,
  'source' : EntityId,
  'target' : EntityId,
  'edgeLabel' : IDL.Text,
  'confidence' : IDL.Float64,
  'relationshipType' : RelationshipType,
});
export const GraphNode = IDL.Record({
  'id' : EntityId,
  'nodeLabel' : IDL.Text,
  'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'entityType' : EntityType,
});
export const GraphData = IDL.Record({
  'edges' : IDL.Vec(GraphEdge),
  'nodes' : IDL.Vec(GraphNode),
});
export const ActivityType = IDL.Variant({
  'documentUploaded' : IDL.Null,
  'complianceChecked' : IDL.Null,
  'entityExtracted' : IDL.Null,
  'relationshipCreated' : IDL.Null,
  'chatCreated' : IDL.Null,
  'documentProcessed' : IDL.Null,
  'incidentRecorded' : IDL.Null,
  'analysisRun' : IDL.Null,
});
export const ActivityItem = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'relatedDocumentId' : IDL.Opt(DocumentId),
  'description' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Severity = IDL.Variant({
  'major' : IDL.Null,
  'minor' : IDL.Null,
  'critical' : IDL.Null,
  'moderate' : IDL.Null,
});
export const FindingStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'inReview' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const ComplianceCheckId = IDL.Nat;
export const ComplianceFinding = IDL.Record({
  'id' : ComplianceCheckId,
  'status' : FindingStatus,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'documentId' : DocumentId,
  'severity' : Severity,
  'findingType' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : ComplianceFinding,
  'err' : AppError,
});
export const IncidentId = IDL.Nat;
export const IncidentRecord = IDL.Record({
  'id' : IncidentId,
  'title' : IDL.Text,
  'sourceDocumentId' : IDL.Opt(DocumentId),
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'severity' : Severity,
  'equipmentId' : IDL.Opt(IDL.Text),
  'incidentType' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : IncidentRecord,
  'err' : AppError,
});
export const ComplianceGap = IDL.Record({
  'requirement' : IDL.Text,
  'missingIn' : IDL.Text,
  'severity' : Severity,
});
export const ComplianceViolation = IDL.Record({
  'violation' : IDL.Text,
  'rule' : IDL.Text,
  'severity' : Severity,
  'location' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ComplianceResult = IDL.Record({
  'checkId' : ComplianceCheckId,
  'gaps' : IDL.Vec(ComplianceGap),
  'generatedAt' : Timestamp,
  'violations' : IDL.Vec(ComplianceViolation),
  'documentId' : DocumentId,
  'complianceScore' : IDL.Float64,
  'riskLevel' : RiskLevel,
  'suggestedCorrections' : IDL.Vec(IDL.Text),
});
export const Result_2 = IDL.Variant({
  'ok' : ComplianceResult,
  'err' : AppError,
});
export const PatternDetection = IDL.Record({
  'occurrenceCount' : IDL.Nat,
  'patternName' : IDL.Text,
  'description' : IDL.Text,
  'affectedEquipment' : IDL.Vec(IDL.Text),
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const PreventiveAction = IDL.Record({
  'action' : IDL.Text,
  'estimatedImpact' : IDL.Text,
  'priority' : Priority,
});
export const RiskCondition = IDL.Record({
  'historicalIncidents' : IDL.Vec(IncidentId),
  'recommendation' : IDL.Text,
  'riskLevel' : RiskLevel,
  'condition' : IDL.Text,
});
export const LessonsLearnedResult = IDL.Record({
  'patterns' : IDL.Vec(PatternDetection),
  'generatedAt' : Timestamp,
  'preventiveActions' : IDL.Vec(PreventiveAction),
  'analysisId' : IDL.Nat,
  'highRiskConditions' : IDL.Vec(RiskCondition),
});
export const SimilarFailure = IDL.Record({
  'incidentId' : IncidentId,
  'date' : IDL.Text,
  'similarityScore' : IDL.Float64,
  'description' : IDL.Text,
  'equipmentId' : IDL.Text,
});
export const EvidenceItem = IDL.Record({
  'documentName' : IDL.Text,
  'relevanceScore' : IDL.Float64,
  'excerpt' : IDL.Text,
  'documentId' : DocumentId,
});
export const CauseAnalysis = IDL.Record({
  'probability' : IDL.Float64,
  'cause' : IDL.Text,
  'supportingEvidence' : IDL.Vec(IDL.Text),
});
export const RootCauseResult = IDL.Record({
  'userQuery' : IDL.Text,
  'recommendedActions' : IDL.Vec(IDL.Text),
  'generatedAt' : Timestamp,
  'similarFailures' : IDL.Vec(SimilarFailure),
  'confidenceScore' : IDL.Float64,
  'evidence' : IDL.Vec(EvidenceItem),
  'equipmentId' : IDL.Opt(IDL.Text),
  'likelyCauses' : IDL.Vec(CauseAnalysis),
});
export const Result_1 = IDL.Variant({ 'ok' : ChatMessage, 'err' : AppError });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatThread' : IDL.Func([IDL.Text], [ChatThread], []),
  'createChunks' : IDL.Func([DocumentId, IDL.Vec(IDL.Text)], [Result_9], []),
  'createEmbedding' : IDL.Func([ChunkId, IDL.Vec(IDL.Float64)], [Result_8], []),
  'createEntity' : IDL.Func(
      [
        IDL.Text,
        EntityType,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Opt(DocumentId),
      ],
      [Result_7],
      [],
    ),
  'createRelationship' : IDL.Func(
      [EntityId, EntityId, RelationshipType, IDL.Float64, IDL.Opt(DocumentId)],
      [Result_6],
      [],
    ),
  'deleteDocument' : IDL.Func([DocumentId], [Result_5], []),
  'extractText' : IDL.Func([DocumentId, IDL.Text], [Result], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func(
      [ChatThreadId],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDocument' : IDL.Func([DocumentId], [Result], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(DocumentSummary)], ['query']),
  'getEntities' : IDL.Func([IDL.Opt(EntityType)], [IDL.Vec(Entity)], ['query']),
  'getGraphData' : IDL.Func(
      [IDL.Opt(EntityId), IDL.Nat],
      [GraphData],
      ['query'],
    ),
  'getRecentActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityItem)], ['query']),
  'getRelationships' : IDL.Func(
      [IDL.Opt(EntityId)],
      [IDL.Vec(Relationship)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordComplianceFinding' : IDL.Func(
      [DocumentId, IDL.Text, IDL.Text, Severity, FindingStatus],
      [Result_4],
      [],
    ),
  'recordIncident' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        Severity,
        IDL.Text,
        IDL.Opt(DocumentId),
      ],
      [Result_3],
      [],
    ),
  'runComplianceCheck' : IDL.Func([DocumentId], [Result_2], []),
  'runLessonsLearnedAnalysis' : IDL.Func([], [LessonsLearnedResult], []),
  'runRootCauseAnalysis' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [RootCauseResult],
      [],
    ),
  'semanticSearch' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(DocumentChunk)],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [
        ChatThreadId,
        MessageRole,
        IDL.Text,
        IDL.Vec(SourceCitation),
        IDL.Opt(IDL.Float64),
      ],
      [Result_1],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatThreadId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const ChatThread = IDL.Record({
    'id' : ChatThreadId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const DocumentId = IDL.Nat;
  const ChunkId = IDL.Nat;
  const DocumentChunk = IDL.Record({
    'id' : ChunkId,
    'content' : IDL.Text,
    'chunkIndex' : IDL.Nat,
    'createdAt' : Timestamp,
    'embedding' : IDL.Opt(IDL.Vec(IDL.Float64)),
    'documentId' : DocumentId,
  });
  const AppError = IDL.Variant({
    'storageError' : IDL.Null,
    'processingError' : IDL.Null,
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(DocumentChunk),
    'err' : AppError,
  });
  const Result_8 = IDL.Variant({ 'ok' : DocumentChunk, 'err' : AppError });
  const EntityType = IDL.Variant({
    'failure' : IDL.Null,
    'asset' : IDL.Null,
    'regulation' : IDL.Null,
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'person' : IDL.Null,
    'event' : IDL.Null,
    'document' : IDL.Null,
    'procedure' : IDL.Null,
    'location' : IDL.Null,
  });
  const EntityId = IDL.Nat;
  const Entity = IDL.Record({
    'id' : EntityId,
    'sourceDocumentId' : IDL.Opt(DocumentId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'entityType' : EntityType,
  });
  const Result_7 = IDL.Variant({ 'ok' : Entity, 'err' : AppError });
  const RelationshipType = IDL.Variant({
    'leadsTo' : IDL.Null,
    'references' : IDL.Null,
    'other' : IDL.Null,
    'violates' : IDL.Null,
    'inspectedBy' : IDL.Null,
    'similarTo' : IDL.Null,
    'compliesWith' : IDL.Null,
    'maintainedBy' : IDL.Null,
    'locatedAt' : IDL.Null,
    'causes' : IDL.Null,
    'partOf' : IDL.Null,
  });
  const RelationshipId = IDL.Nat;
  const Relationship = IDL.Record({
    'id' : RelationshipId,
    'sourceDocumentId' : IDL.Opt(DocumentId),
    'createdAt' : Timestamp,
    'sourceId' : EntityId,
    'confidence' : IDL.Float64,
    'targetId' : EntityId,
    'relationshipType' : RelationshipType,
  });
  const Result_6 = IDL.Variant({ 'ok' : Relationship, 'err' : AppError });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError });
  const DocumentStatus = IDL.Variant({
    'chunked' : IDL.Null,
    'error' : IDL.Null,
    'extracted' : IDL.Null,
    'uploaded' : IDL.Null,
    'processing' : IDL.Null,
    'embedded' : IDL.Null,
    'ready' : IDL.Null,
  });
  const DocumentMetadata = IDL.Record({
    'assetNames' : IDL.Vec(IDL.Text),
    'fileSize' : IDL.Nat,
    'personnel' : IDL.Vec(IDL.Text),
    'failureTypes' : IDL.Vec(IDL.Text),
    'maintenanceEvents' : IDL.Vec(IDL.Text),
    'safetyReferences' : IDL.Vec(IDL.Text),
    'dates' : IDL.Vec(IDL.Text),
    'pageCount' : IDL.Opt(IDL.Nat),
    'equipmentIds' : IDL.Vec(IDL.Text),
    'regulatoryReferences' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : DocumentId,
    'status' : DocumentStatus,
    'owner' : IDL.Principal,
    'metadata' : DocumentMetadata,
    'blob' : ExternalBlob,
    'createdAt' : Timestamp,
    'mimeType' : IDL.Text,
    'extractedText' : IDL.Opt(IDL.Text),
    'filename' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const Result = IDL.Variant({ 'ok' : Document, 'err' : AppError });
  const ChatMessageId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const SourceCitation = IDL.Record({
    'documentName' : IDL.Text,
    'chunkIndex' : IDL.Nat,
    'excerpt' : IDL.Text,
    'documentId' : DocumentId,
  });
  const ChatMessage = IDL.Record({
    'id' : ChatMessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
    'sources' : IDL.Vec(SourceCitation),
    'confidence' : IDL.Opt(IDL.Float64),
    'threadId' : ChatThreadId,
  });
  const DashboardStats = IDL.Record({
    'totalChatThreads' : IDL.Nat,
    'totalComplianceChecks' : IDL.Nat,
    'recentUploads' : IDL.Nat,
    'totalEntities' : IDL.Nat,
    'totalIncidents' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
    'documentsProcessed' : IDL.Nat,
    'totalRelationships' : IDL.Nat,
  });
  const DocumentSummary = IDL.Record({
    'id' : DocumentId,
    'status' : DocumentStatus,
    'createdAt' : Timestamp,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const GraphEdge = IDL.Record({
    'id' : RelationshipId,
    'source' : EntityId,
    'target' : EntityId,
    'edgeLabel' : IDL.Text,
    'confidence' : IDL.Float64,
    'relationshipType' : RelationshipType,
  });
  const GraphNode = IDL.Record({
    'id' : EntityId,
    'nodeLabel' : IDL.Text,
    'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'entityType' : EntityType,
  });
  const GraphData = IDL.Record({
    'edges' : IDL.Vec(GraphEdge),
    'nodes' : IDL.Vec(GraphNode),
  });
  const ActivityType = IDL.Variant({
    'documentUploaded' : IDL.Null,
    'complianceChecked' : IDL.Null,
    'entityExtracted' : IDL.Null,
    'relationshipCreated' : IDL.Null,
    'chatCreated' : IDL.Null,
    'documentProcessed' : IDL.Null,
    'incidentRecorded' : IDL.Null,
    'analysisRun' : IDL.Null,
  });
  const ActivityItem = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'relatedDocumentId' : IDL.Opt(DocumentId),
    'description' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const Severity = IDL.Variant({
    'major' : IDL.Null,
    'minor' : IDL.Null,
    'critical' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const FindingStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inReview' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const ComplianceCheckId = IDL.Nat;
  const ComplianceFinding = IDL.Record({
    'id' : ComplianceCheckId,
    'status' : FindingStatus,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'documentId' : DocumentId,
    'severity' : Severity,
    'findingType' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : ComplianceFinding, 'err' : AppError });
  const IncidentId = IDL.Nat;
  const IncidentRecord = IDL.Record({
    'id' : IncidentId,
    'title' : IDL.Text,
    'sourceDocumentId' : IDL.Opt(DocumentId),
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'severity' : Severity,
    'equipmentId' : IDL.Opt(IDL.Text),
    'incidentType' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : IncidentRecord, 'err' : AppError });
  const ComplianceGap = IDL.Record({
    'requirement' : IDL.Text,
    'missingIn' : IDL.Text,
    'severity' : Severity,
  });
  const ComplianceViolation = IDL.Record({
    'violation' : IDL.Text,
    'rule' : IDL.Text,
    'severity' : Severity,
    'location' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ComplianceResult = IDL.Record({
    'checkId' : ComplianceCheckId,
    'gaps' : IDL.Vec(ComplianceGap),
    'generatedAt' : Timestamp,
    'violations' : IDL.Vec(ComplianceViolation),
    'documentId' : DocumentId,
    'complianceScore' : IDL.Float64,
    'riskLevel' : RiskLevel,
    'suggestedCorrections' : IDL.Vec(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : ComplianceResult, 'err' : AppError });
  const PatternDetection = IDL.Record({
    'occurrenceCount' : IDL.Nat,
    'patternName' : IDL.Text,
    'description' : IDL.Text,
    'affectedEquipment' : IDL.Vec(IDL.Text),
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PreventiveAction = IDL.Record({
    'action' : IDL.Text,
    'estimatedImpact' : IDL.Text,
    'priority' : Priority,
  });
  const RiskCondition = IDL.Record({
    'historicalIncidents' : IDL.Vec(IncidentId),
    'recommendation' : IDL.Text,
    'riskLevel' : RiskLevel,
    'condition' : IDL.Text,
  });
  const LessonsLearnedResult = IDL.Record({
    'patterns' : IDL.Vec(PatternDetection),
    'generatedAt' : Timestamp,
    'preventiveActions' : IDL.Vec(PreventiveAction),
    'analysisId' : IDL.Nat,
    'highRiskConditions' : IDL.Vec(RiskCondition),
  });
  const SimilarFailure = IDL.Record({
    'incidentId' : IncidentId,
    'date' : IDL.Text,
    'similarityScore' : IDL.Float64,
    'description' : IDL.Text,
    'equipmentId' : IDL.Text,
  });
  const EvidenceItem = IDL.Record({
    'documentName' : IDL.Text,
    'relevanceScore' : IDL.Float64,
    'excerpt' : IDL.Text,
    'documentId' : DocumentId,
  });
  const CauseAnalysis = IDL.Record({
    'probability' : IDL.Float64,
    'cause' : IDL.Text,
    'supportingEvidence' : IDL.Vec(IDL.Text),
  });
  const RootCauseResult = IDL.Record({
    'userQuery' : IDL.Text,
    'recommendedActions' : IDL.Vec(IDL.Text),
    'generatedAt' : Timestamp,
    'similarFailures' : IDL.Vec(SimilarFailure),
    'confidenceScore' : IDL.Float64,
    'evidence' : IDL.Vec(EvidenceItem),
    'equipmentId' : IDL.Opt(IDL.Text),
    'likelyCauses' : IDL.Vec(CauseAnalysis),
  });
  const Result_1 = IDL.Variant({ 'ok' : ChatMessage, 'err' : AppError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatThread' : IDL.Func([IDL.Text], [ChatThread], []),
    'createChunks' : IDL.Func([DocumentId, IDL.Vec(IDL.Text)], [Result_9], []),
    'createEmbedding' : IDL.Func(
        [ChunkId, IDL.Vec(IDL.Float64)],
        [Result_8],
        [],
      ),
    'createEntity' : IDL.Func(
        [
          IDL.Text,
          EntityType,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Opt(DocumentId),
        ],
        [Result_7],
        [],
      ),
    'createRelationship' : IDL.Func(
        [
          EntityId,
          EntityId,
          RelationshipType,
          IDL.Float64,
          IDL.Opt(DocumentId),
        ],
        [Result_6],
        [],
      ),
    'deleteDocument' : IDL.Func([DocumentId], [Result_5], []),
    'extractText' : IDL.Func([DocumentId, IDL.Text], [Result], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [ChatThreadId],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDocument' : IDL.Func([DocumentId], [Result], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(DocumentSummary)], ['query']),
    'getEntities' : IDL.Func(
        [IDL.Opt(EntityType)],
        [IDL.Vec(Entity)],
        ['query'],
      ),
    'getGraphData' : IDL.Func(
        [IDL.Opt(EntityId), IDL.Nat],
        [GraphData],
        ['query'],
      ),
    'getRecentActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityItem)],
        ['query'],
      ),
    'getRelationships' : IDL.Func(
        [IDL.Opt(EntityId)],
        [IDL.Vec(Relationship)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordComplianceFinding' : IDL.Func(
        [DocumentId, IDL.Text, IDL.Text, Severity, FindingStatus],
        [Result_4],
        [],
      ),
    'recordIncident' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          Severity,
          IDL.Text,
          IDL.Opt(DocumentId),
        ],
        [Result_3],
        [],
      ),
    'runComplianceCheck' : IDL.Func([DocumentId], [Result_2], []),
    'runLessonsLearnedAnalysis' : IDL.Func([], [LessonsLearnedResult], []),
    'runRootCauseAnalysis' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [RootCauseResult],
        [],
      ),
    'semanticSearch' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(DocumentChunk)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [
          ChatThreadId,
          MessageRole,
          IDL.Text,
          IDL.Vec(SourceCitation),
          IDL.Opt(IDL.Float64),
        ],
        [Result_1],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };