/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be directly edited.

import { createFileRoute as _createFileRoute } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";
import { Route as ComplianceRoute } from "./routes/compliance";
import { Route as CopilotRoute } from "./routes/copilot";
import { Route as DocumentsRoute } from "./routes/documents";
import { Route as GraphRoute } from "./routes/graph";
import { Route as IndexRoute } from "./routes/index";
import { Route as LessonsRoute } from "./routes/lessons";
import { Route as RcaRoute } from "./routes/rca";
import { Route as SettingsRoute } from "./routes/settings";

const rootTree = rootRoute.addChildren([
  IndexRoute,
  DocumentsRoute,
  CopilotRoute,
  GraphRoute,
  RcaRoute,
  ComplianceRoute,
  LessonsRoute,
  SettingsRoute,
]);

export const routeTree = rootTree;

export type FileRoutesByPath = {
  "/": typeof IndexRoute;
  "/documents": typeof DocumentsRoute;
  "/copilot": typeof CopilotRoute;
  "/graph": typeof GraphRoute;
  "/rca": typeof RcaRoute;
  "/compliance": typeof ComplianceRoute;
  "/lessons": typeof LessonsRoute;
  "/settings": typeof SettingsRoute;
};

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/documents": {
      preLoaderRoute: typeof DocumentsRoute;
      parentRoute: typeof rootRoute;
    };
    "/copilot": {
      preLoaderRoute: typeof CopilotRoute;
      parentRoute: typeof rootRoute;
    };
    "/graph": {
      preLoaderRoute: typeof GraphRoute;
      parentRoute: typeof rootRoute;
    };
    "/rca": {
      preLoaderRoute: typeof RcaRoute;
      parentRoute: typeof rootRoute;
    };
    "/compliance": {
      preLoaderRoute: typeof ComplianceRoute;
      parentRoute: typeof rootRoute;
    };
    "/lessons": {
      preLoaderRoute: typeof LessonsRoute;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      preLoaderRoute: typeof SettingsRoute;
      parentRoute: typeof rootRoute;
    };
  }
}
